Repository googleapis/java-datacatalog, pull requests merged in 2020-09, with the labels that each got.

#269 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: datacatalog, cla: yes, context: full

#270 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#272 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#284 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#288 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: datacatalog, automerge, cla: yes

#294 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#296 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
