Repository googleapis/java-datacatalog, pull requests merged in 2020-06, with the labels that each got.

#199 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#201 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#207 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#208 docs: change relative URLs to absolute URLs to fix broken links.
  proto-google-cloud-datacatalog-v1/src/main/java/com/google/cloud/datacatalog/v1/GcsFilesetSpec.java
  proto-google-cloud-datacatalog-v1/src/main/java/com/google/cloud/datacatalog/v1/GcsFilesetSpecOrBuilder.java
  proto-google-cloud-datacatalog-v1/src/main/proto/google/cloud/datacatalog/v1/gcs_fileset_spec.proto
  proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/v1beta1/GcsFilesetSpec.java
  proto-google-cloud-datacatalog-v1beta1/src/main/java/com/google/cloud/datacatalog/v1beta1/GcsFilesetSpecOrBuilder.java
  proto-google-cloud-datacatalog-v1beta1/src/main/proto/google/cloud/datacatalog/v1beta1/gcs_fileset_spec.proto
  synth.metadata
Labels: automerge, cla: yes, context: full

#216 chore: update README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#219 ci: switch to secret manager for sample/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#215 feat(deps): use google-cloud-shared-dependencies and flatten-maven-plugin
  .gitignore
  google-cloud-datacatalog/pom.xml
  grpc-google-cloud-datacatalog-v1/pom.xml
  grpc-google-cloud-datacatalog-v1beta1/pom.xml
  pom.xml
  proto-google-cloud-datacatalog-v1/pom.xml
  proto-google-cloud-datacatalog-v1beta1/pom.xml
Labels: cla: yes

#220 feat: promote to GA
  .repo-metadata.json
  README.md
  synth.metadata
Labels: cla: yes

#223 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  pom.xml
Labels: cla: yes

#229 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#238 fix: migrate to grpc_service_config
  README.md
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/stub/DataCatalogStubSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/DataCatalogClient.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/DataCatalogSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/package-info.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/DataCatalogStub.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/DataCatalogStubSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/GrpcDataCatalogStub.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/PolicyTagManagerSerializationStubSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/PolicyTagManagerStubSettings.java
  google-cloud-datacatalog/src/test/java/com/google/cloud/datacatalog/v1beta1/DataCatalogClientTest.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#240 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
