Repository googleapis/java-datacatalog, pull requests merged in 2021-05, with the labels that each got.

#517 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: datacatalog, automerge, cla: yes, context: none

#518 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: datacatalog, automerge, cla: yes

#519 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: datacatalog, automerge, cla: yes, context: full

#526 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datacatalog, automerge, cla: yes

#528 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datacatalog, automerge, cla: yes

#527 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: datacatalog, automerge, cla: yes, context: full

#530 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datacatalog, automerge, cla: yes

#531 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: datacatalog, automerge, cla: yes, context: full

#533 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: datacatalog, automerge, cla: yes, context: full

#536 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: datacatalog, automerge, cla: yes, context: full

#540 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datacatalog, automerge, cla: yes

#541 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: datacatalog, automerge, cla: yes
