Repository googleapis/java-datacatalog, pull requests merged in 2021-08, with the labels that each got.

#588 chore: remove java 7 units check
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: datacatalog, automerge, context: full

#596 chore: remove java7 units check from required checks in master
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: datacatalog, automerge

#599 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: datacatalog, automerge

#601 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: datacatalog, automerge

#607 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: datacatalog, automerge

#609 build(java): use ENABLE_FLAKYBOT env variable
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  synth.metadata
Labels: cla: yes, api: datacatalog, automerge, context: full

#611 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: datacatalog, automerge

#613 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: datacatalog, automerge

#614 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: datacatalog, automerge

#620 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: datacatalog, automerge

#619 ci: removing linkage-monitor from the required checks
  .github/sync-repo-settings.yaml
Labels: cla: yes, api: datacatalog, automerge

#622 ci: removing linkage-monitor from the required checks
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: datacatalog, automerge, context: full

#604 chore: Re-generated to pick up changes from googleapis
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/DataCatalogClient.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/DataCatalogSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/PolicyTagManagerClient.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/PolicyTagManagerSerializationSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/PolicyTagManagerSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/stub/DataCatalogStubSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/stub/GrpcDataCatalogStub.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/stub/GrpcPolicyTagManagerSerializationStub.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/stub/GrpcPolicyTagManagerStub.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/stub/PolicyTagManagerSerializationStubSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/stub/PolicyTagManagerStubSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/DataCatalogClient.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/DataCatalogSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/PolicyTagManagerClient.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/PolicyTagManagerSerializationSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/PolicyTagManagerSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/DataCatalogStubSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/GrpcDataCatalogStub.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/GrpcPolicyTagManagerSerializationStub.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/GrpcPolicyTagManagerStub.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/PolicyTagManagerSerializationStubSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/PolicyTagManagerStubSettings.java
  synth.metadata
Labels: cla: yes, api: datacatalog, context: full

#625 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: datacatalog, automerge

#626 chore: re-generated to pick up changes from googleapis
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/DataCatalogClient.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/stub/DataCatalogStubSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/stub/PolicyTagManagerSerializationStubSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1/stub/PolicyTagManagerStubSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/DataCatalogStubSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/PolicyTagManagerSerializationStubSettings.java
  google-cloud-datacatalog/src/main/java/com/google/cloud/datacatalog/v1beta1/stub/PolicyTagManagerStubSettings.java
  proto-google-cloud-datacatalog-v1/src/main/java/com/google/cloud/datacatalog/v1/SearchCatalogRequest.java
  proto-google-cloud-datacatalog-v1/src/main/java/com/google/cloud/datacatalog/v1/SearchCatalogRequestOrBuilder.java
  proto-google-cloud-datacatalog-v1/src/main/proto/google/cloud/datacatalog/v1/datacatalog.proto
  synth.metadata
Labels: cla: yes, api: datacatalog, context: full

#628 build(java): update renovate config to mark conformance tests as a test commit type
  renovate.json
  synth.metadata
Labels: cla: yes, api: datacatalog, automerge, context: full
